// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdJDVsqMdb0RZHXKTeZQt1D7aoA6jpGW0',
    appId: '1:512305095847:web:ef50b38aa89b2c806be782',
    messagingSenderId: '512305095847',
    projectId: 'nike-shoes-apparel-stories',
    authDomain: 'nike-shoes-apparel-stories.firebaseapp.com',
    storageBucket: 'nike-shoes-apparel-stories.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhteCT4WkKQjUkvdqCzfAL11xCUN9o3KQ',
    appId: '1:512305095847:android:0bb65cb61a29e47a6be782',
    messagingSenderId: '512305095847',
    projectId: 'nike-shoes-apparel-stories',
    storageBucket: 'nike-shoes-apparel-stories.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq1loib5Acoa8euvrXTEV0dQsqAyjait4',
    appId: '1:512305095847:ios:2e769e16b44497bf6be782',
    messagingSenderId: '512305095847',
    projectId: 'nike-shoes-apparel-stories',
    storageBucket: 'nike-shoes-apparel-stories.firebasestorage.app',
    iosBundleId: 'com.example.nike',
  );
}
